name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - name: Nix build
      run: |
        nix-build release.nix
        ./dist/build/site/site build
